language: go
sudo: false

env:
  global:
    - GO111MODULE=on

go:
- 1.12.x
- master

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
- go get golang.org/x/lint/golint
- make confg="config-spencedy.env" go-dependencies

services:
  docker

script:
- make config="config-spencedy.env" verify
- make config="config-spencedy.env" docker-build
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make config="config-spencedy.env" docker-push
- if [[ $TRAVIS_PULL_REQUEST == false] && [ $TRAVIS_BRANCH == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
      make config="config-spencedy.env" docker-release-version && \
      make config="config-spencedy.env" docker-release-latest
  fi

cache:
  directories:
    - vendor
